CREATE TABLE EMPRESA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    ATIVO BOOLEAN NOT NULL
);

CREATE TABLE PESSOA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DOCUMENTO VARCHAR(255),
    DDI VARCHAR(5) NOT NULL,
    DDD VARCHAR(5) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    WHATSAPP VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255),
    PONTOS INT,
    CORRENTISTA BOOLEAN NOT NULL,
    FOREIGN KEY (ID_EMPRESA) RESFERENCES EMPRESA (ID)
);

CREATE TABLE FILIAL (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    INSC_ESTADUAL VARCHAR(255) NOT NULL,
    INSC_MUNICIPAL VARCHAR(255) NOT NULL,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    PAIS VARCHAR(255) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    CEP VARCHAR(255) NOT NULL,
    RUA VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    COMPLEMENTO VARCHAR(255),
    DDI VARCHAR(5) NOT NULL,
    DDD VARCHAR(5) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    WHATSAPP VARCHAR(20),
    EMAIL VARCHAR(255) NOT NULL,
    LOGO VARCHAR(255),
    ATIVO BOOLEAN NOT NULL,
    DOCUMENTO VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE FORMA_PAG (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_FILIAL INT NOT NULL,
    NOME VARCHAR(255),
    FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL (ID)
);

CREATE TABLE HORARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_FILIAL INT NOT NULL,
    SEGUNDA_INICIO VARCHAR(5),
    SEGUNDA_FIM VARCHAR(5),
    TERCA_INICIO VARCHAR(5),
    TERCA_FIM VARCHAR(5),
    QUARTA_INICIO VARCHAR(5),
    QUARTA_FIM VARCHAR(5),
    QUINTA_INICIO VARCHAR(5),
    QUINTA_FIM VARCHAR(5),
    SEXTA_INICIO VARCHAR(5),
    SEXTA_FIM VARCHAR(5),
    SABADO_INICIO VARCHAR(5),
    SABADO_FIM VARCHAR(5),
    DOMINGO_INICIO VARCHAR(5),
    DOMINGO_FIM VARCHAR(5),
    FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL (ID)
);

CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE NIVEL_ACESSO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255),
    ADMIN BOOLEAN NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE NIVEL_ACESSO_PERMISSAO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_NIVEL_ACESSO INT NOT NULL,
    PERMISSAO VARCHAR(255) NOT NULL,
    LIBERADO BOOLEAN NOT NULL,
    FOREIGN KEY (ID_NIVEL_ACESSO) REFERENCES NIVEL_ACESSO (ID)
);

CREATE TABLE FILIAL_USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_FILIAL INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_NIVEL_ACESSO INT NOT NULL,
    FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL (ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
    FOREIGN KEY (ID_NIVEL_ACESSO) REFERENCES NIVEL_ACESSO (ID)
);

CREATE TABLE PRODUTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CODIGO_INTERNO VARCHAR(255),
    CODIGO_BARRAS VARCHAR(255),
    IMAGEM VARCHAR(255),
    OBS VARCHAR(255),
    VISIVEL_PDV BOOLEAN NOT NULL,
    VISIVEL_COMANDA BOOLEAN NOT NULL,
    VISIVEL_CARDAPIO BOOLEAN NOT NULL,
    CONTROLE_ESTOQUE BOOLEAN NOT NULL,
    EXPED INT DEFAULT 0,
    PRECO_01 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_02 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_03 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_04 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_05 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_06 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_07 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_08 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_09 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_10 DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ESTOQUE DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRECO_CUSTO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID),
);

CREATE TABLE FILIAL_PRODUTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_FILIAL INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    PRECO_01 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_02 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_03 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_04 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_05 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_06 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_07 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_08 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_09 DECIMAL(10, 2) DEFAULT NULL,
    PRECO_10 DECIMAL(10, 2) DEFAULT NULL,
    ESTOQUE DECIMAL(10, 2) DEFAULT NULL,
    FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL (ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);